[workspace]
resolver = "2"
members = [
    "examples",
    "pg2any-lib"
]

[workspace.package]
edition = "2021"
authors = ["danielshih <dog830228@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/isdaniel/pg2any"
homepage = "https://github.com/isdaniel/pg2any"
documentation = "https://docs.rs/pg2any_lib"
readme = "README.md"
categories = ["database", "asynchronous", "development-tools"]
keywords = ["postgresql", "cdc", "replication", "database", "streaming"]

[workspace.dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = { version = "0.7.16", features = ["compat"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
chrono = { version = "0.4.41", features = ["serde"] }
bytes = "1.10.1"
async-trait = "0.1.88"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tiberius = { version = "0.12", features = ["tds73", "sql-browser-tokio", "bigdecimal", "rust_decimal", "time", "chrono"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "mysql", "sqlite", "chrono", "uuid"] }
libpq-sys = "0.8"
# Monitoring and metrics dependencies
prometheus = { version = "0.14.0", features = ["process"] }
lazy_static = "1.5"
hyper = { version = "1.7", features = ["full"] }
hyper-util = { version = "0.1.16", features = ["full"] }
http-body-util = "0.1.3"
tikv-jemalloc-ctl = { version = "0.6.1", features = ["stats", "use_std"] }
pg_walstream = "0.0.1"
